apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: crafty-pvc
  labels:
    app: crafty
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.crafty.storage }}
