{{- if and .Values.persistence.enabled (not .Values.persistence.existingClaim) }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
 name: crafty-pvc
 labels:
   {{- include ".Values.crafty.storage.labels" . | nindent 4 }}  
spec:
 storageClassName: {{ .Values.crafty.storage.storageClass }}
 accessModes:
   - {{ .Values.crafty.storage.accessMode | quote }}
 resources:
   requests:
     storage: {{ .Values.crafty.storage.size | quote }}
 {{- end }}
 
