apiVersion: apps/v1
kind: Deployment
metadata:
  name: crafty-deployment
  labels:
    app: crafty
    scope: games
spec:
  replicas: {{ .Values.replicaCount }}
{{- if .Values.strategyType }}
  strategy:
    type: {{ .Values.strategyType | quote }}
{{- end }}
  selector:
    matchLabels:
      app: crafty
      scope: games
  template:
    metadata:
      labels:
        app: crafty
        scope: games
    spec:
      imagePullSecrets:
{{ toYaml .Values.image.secrets | indent 10 }}
      containers:
      - name: crafty
        image: {{ template "imagename" . }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: maps
          containerPort: 8123
        - name: web
          containerPort: 8443
        - name: minecraft1
          containerPort: 25565
          hostPort: 25565
        - name: minecraft2
          containerPort: 25566
          hostPort: 25566
        - name: minecraft3
          containerPort: 25567
          hostPort: 25567
        volumeMounts:
        - name: crafty-data
          mountPath: /crafty/backups
          subPath: backups
        - name: crafty-data
          mountPath: /crafty/logs
          subPath: logs
        - name: crafty-data
          mountPath: /crafty/servers
          subPath: servers
        - name: crafty-data
          mountPath: /crafty/import
          subPath: import
        - name: crafty-data
          mountPath: /crafty//app/config
          subPath: config
      volumes:
      - name: crafty-data
        persistentVolumeClaim:
          claimName: crafty-pvc
