apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: crafty-ingress
  labels:
    app: crafty
    scope: games
spec:
  rules:
  - host: {{ .Values.crafty.ingress.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: crafty
            port:
              number: 8443
  - host: {{ .Values.crafty.ingress.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: crafty
            port:
              number: 8123
