kind: PersistentVolumeClaim
apiVersion: v1
metadata:
 name: crafty-pvc
 labels:
    app: crafty
    scope: games
spec:
 storageClassName: {{ .Values.crafty.storage.storageClass }}
 accessModes:
   - {{ .Values.crafty.storage.accessMode | quote }}
 resources:
   requests:
     storage: {{ .Values.crafty.storage.size | quote }}
 
